---
title: "tester_2.0"
author: "William Norfolk"
date: "8/27/2020"
output: html_document
---

Load in Libs
```{r}
library(broom)
library(ggpubr)
library(tidyverse)
library(mgcv)
library(plotly)
```

Read in raw data from RDS.

```{r}
raw_data <- readRDS("./n1_n2_cleaned_cases.rds")

final_data <- raw_data %>% mutate(log_copy_per_L = log10(mean_copy_num_L)) %>%
  rename(Facility = wrf) %>%
  mutate(Facility = recode(Facility, 
                           "NO" = "WRF A",
                           "MI" = "WRF B",
                           "CC" = "WRF C"))
```

Data split for main figure

```{r}
#split data to layer for main plotly figure
only_positives <<- subset(final_data, (!is.na(final_data$Facility)))
only_n1 <- subset(only_positives, target == "N1")
only_n2 <- subset(only_positives, target == "N2")
only_background <<-final_data %>% 
  select(c(date, cases_cum_clarke, new_cases_clarke, X10_day_ave_clarke, cases_per_100000_clarke)) %>%
  group_by(date) %>% summarise_if(is.numeric, mean)



#specify fun colors
background_color <- "#7570B3"
ten_day_ave_color <- "#E6AB02"
marker_colors <- c("N1" = '#1B9E77',"N2" ='#D95F02')
```

```{r}
#creates the two panels of the main figure
        p1 <- only_background %>%
              plotly::plot_ly() %>%
              plotly::add_trace(x = ~date, y = ~new_cases_clarke, 
                                type = "bar", 
                                hoverinfo = "text",
                                text = ~paste('</br> Date: ', date,
                                                     '</br> Daily Cases: ', new_cases_clarke),
                                alpha = 0.5,
                                name = "Daily Reported Cases",
                                color = background_color,
                                colors = background_color,
                                showlegend = FALSE) %>%
            layout(yaxis = list(title = "Athens Daily Cases", range = c(0,80), showline=TRUE)) %>%
            layout(legend = list(orientation = "h", x = 0.2, y = -0.3))
        
        #renders the main plot layer two as ten day moving average
        p1 <- p1 %>% plotly::add_trace(x = ~date, y = ~X10_day_ave_clarke, 
                             type = "scatter",
                             mode = "lines",
                             hoverinfo = "text",
                            text = ~paste('</br> Date: ', date,
                                                     '</br> Ten-Day Moving Average: ', X10_day_ave_clarke),
                             name = "Ten Day Moving Average Athens",
                             line = list(color = ten_day_ave_color),
                             showlegend = FALSE)
        
        #renders the main plot layer three as positive target hits
        p2 <- plotly::plot_ly() %>%
          plotly::add_trace(x = ~date, y = ~mean_copy_num_L,
                                       type = "scatter",
                                       mode = "markers",
                                       hoverinfo = "text",
                                       text = ~paste('</br> Date: ', date,
                                                     '</br> Facility: ', Facility,
                                                     '</br> Target: ', target,
                                                     '</br> Copies/L: ', round(mean_copy_num_L, digits = 2)),
                                       data = only_n1,
                                       symbol = ~Facility,
                                       marker = list(color = '#1B9E77', size = 8, opacity = 0.65),
                                       showlegend = FALSE) %>%
          plotly::add_trace(x = ~date, y = ~mean_copy_num_L,
                                       type = "scatter",
                                       mode = "markers",
                                       hoverinfo = "text",
                                       text = ~paste('</br> Date: ', date,
                                                     '</br> Facility: ', Facility,
                                                     '</br> Target: ', target,
                                                     '</br> Copies/L: ', round(mean_copy_num_L, digits = 2)),
                                       data = only_n2,
                                       symbol = ~Facility,
                                       marker = list(color = '#D95F02', size = 8, opacity = 0.65),
                                       showlegend = FALSE) %>%
            layout(yaxis = list(title = "SARS CoV-2 Copies/L", 
                                 range = c(3, 8), showline = TRUE,
                                 type = "log",
                                 automargin = TRUE)) %>%
            layout(legend = list(orientation = "h", x = 0.2, y = -0.3))
        
        #adds LOD line
        p2 <- p2 %>% plotly::add_segments(x = as.Date("2020-03-14"), 
                                          xend = ~max(date + 10), 
                                          y = 3571.429, yend = 3571.429,
                                          opacity = 0.35,
                                          line = list(color = "black", dash = "dash")) %>%
          layout(annotations = list(x = as.Date("2020-03-28"), y = 3.8, xref = "x", yref = "y", 
                                    text = "Limit of Detection", showarrow = FALSE))

        

        p1
        p2
```


```{r}
#create smoothing data frames 
#n1
smooth_n1 <- only_n1 %>% select(-c(Facility)) %>% 
  group_by(date, cases_cum_clarke, new_cases_clarke, X10_day_ave_clarke, cases_per_100000_clarke) %>%
  summarize(sum_copy_num_L = sum(mean_total_copies)) %>%
  ungroup() %>%
  mutate(log_sum_copies_L = log10(sum_copy_num_L)) %>%
  mutate(target = "N1")

#n2
smooth_n2 <- only_n2 %>% select(-c(Facility)) %>% 
  group_by(date, cases_cum_clarke, new_cases_clarke, X10_day_ave_clarke, cases_per_100000_clarke) %>%
  summarize(sum_copy_num_L = sum(mean_total_copies)) %>%
  ungroup() %>%
  mutate(log_sum_copies_L = log10(sum_copy_num_L)) %>%
  mutate(target = "N2")

#loess at 0.80 span (same as ggplot default)
sumfit_1 <- loess(log_sum_copies_L ~ new_cases_clarke, data = smooth_n1, span = 0.8)
sumfit_2 <- loess(log_sum_copies_L ~ new_cases_clarke, data = smooth_n2, span = 0.8)
#generalized additive model 
sumfit_3 <- gam(smooth_n1$log_sum_copies_L ~ smooth_n1$new_cases_clarke)
sumfit_4 <- gam(smooth_n2$log_sum_copies_L ~ smooth_n2$new_cases_clarke)
#generalized linear model
sumfit_5 <- glm(log_sum_copies_L ~ new_cases_clarke, data = smooth_n1)
sumfit_6 <- glm(log_sum_copies_L ~ new_cases_clarke, data = smooth_n2)

p3 <- plotly::plot_ly() %>%
  plotly::add_trace(x = ~date, y = ~log_sum_copies_L,
                    type = "scatter",
                    mode = "markers",
                    hoverinfo = "text",
                    text = ~paste('</br> Date: ', date,
                                  '</br> Copies/L: ', round(log_sum_copies_L, digits = 2)),
                    data = smooth_n1,
                    marker = list(color = '#1B9E77', size = 8, opacity = 0.65),
                    showlegend = FALSE) %>%
  plotly::add_trace(x = ~date, y = ~log_sum_copies_L,
                    type = "scatter",
                    mode = "markers",
                    hoverinfo = "text",
                    text = ~paste('</br> Date: ', date,
                                  '</br> Copies/L: ', round(log_sum_copies_L, digits = 2)),
                    data = smooth_n2,
                    marker = list(color = '#D95F02', size = 8, opacity = 0.65),
                    showlegend = FALSE) %>%
  plotly::add_lines(x = ~date, y = predict(sumfit_1),
                    data = smooth_n1,
                    hoverinfo = "text",
                    text = NULL,
                    showlegend = FALSE,
                    line = list(color = '#1B9E77')) %>%
  plotly::add_lines(x = ~date, y = predict(sumfit_2),
                    data = smooth_n2,
                    hoverinfo = "text",
                    text = NULL,
                    showlegend = FALSE,
                    line = list(color = '#D95F02'))%>%
              layout(yaxis = list(title = "Log SARS CoV-2 Copies/L", 
                                 showline = TRUE,
                                 automargin = TRUE))
  


p3
```


```{r}
test12 <-
    plotly::subplot(p3,p1, # plots to combine, top to bottom
      nrows = 2,
      heights = c(.6,.4),  # relative heights of the two plots
      shareX = TRUE,  # plots will share an X axis
      titleY = TRUE
    ) %>%
    # create a vertical "spike line" to compare data across 2 plots
    plotly::layout(
      xaxis = list(
        spikethickness = 1,
        spikedash = "dot",
        spikecolor = "black",
        spikemode = "across+marker",
        spikesnap = "cursor"
      ),
      yaxis = list(spikethickness = 0)
    )

test12
```


```{r}
#make a dataframe to average both genes, remove target column, group by date, then average
both_clean <- full_join(smooth_n1, smooth_n2) %>%
  select(-c(target)) %>%
  group_by(date) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup()

combofit_1 <- loess(log_sum_copies_L ~ new_cases_clarke, data = both_clean, span = 0.8)
combofit_2 <- lm(log_sum_copies_L ~ new_cases_clarke, data = both_clean)

```


```{r}
p4 <- plotly::plot_ly() %>%
  plotly::add_trace(x = ~date, y = ~log_sum_copies_L,
                    type = "scatter",
                    mode = "markers",
                    hoverinfo = "text",
                    text = ~paste('</br> Date: ', date,
                                  '</br> Copies/L: ', round(log_sum_copies_L, digits = 2)),
                    data = both_clean,
                    marker = list(color = '#1B9E77', size = 8, opacity = 0.65),
                    showlegend = FALSE) %>%
    plotly::add_lines(x = ~date, y = predict(combofit_1),
                    data = both_clean,
                    hoverinfo = "text",
                    text = NULL,
                    showlegend = FALSE,
                    line = list(color = '#1B9E77'))%>%
              layout(yaxis = list(title = "Log SARS CoV-2 Copies/L", 
                                 showline = TRUE,
                                 automargin = TRUE))
  

p4

#make a plot that stacks the averge of both genes
test1234 <-
    plotly::subplot(p4,p1, # plots to combine, top to bottom
      nrows = 2,
      heights = c(.6,.4),  # relative heights of the two plots
      shareX = TRUE,  # plots will share an X axis
      titleY = TRUE
    ) %>%
    # create a vertical "spike line" to compare data across 2 plots
    plotly::layout(
      xaxis = list(
        spikethickness = 1,
        spikedash = "dot",
        spikecolor = "black",
        spikemode = "across+marker",
        spikesnap = "cursor"
      ),
      yaxis = list(spikethickness = 0)
    )

test1234
```

```{r}
#add trendlines 
#extract data from geom_smooth
#n1 extract
cc <- ggplot(smooth_n1, aes(x = date, y = log_sum_copies_L)) + 
  stat_smooth(aes(outfit=fit_n1<<-..y..), color = '#1B9E77', span = 0.8)
#n2 extract
oo <- ggplot(smooth_n2, aes(x = date, y = log_sum_copies_L)) + 
  stat_smooth(aes(outfit=fit_n2<<-..y..), color = '#1B9E77', span = 0.8)

#look at the fits to align dates and total observations
#n1
cc
fit_n1
#n2
oo
fit_n2

#assign fits to a vector
n1_trend <- fit_n1
n2_trend <- fit_n2

#reassign dataframes (just to be safe)
work_n1 <- smooth_n1
work_n2 <- smooth_n2

#fill in missing dates to smooth fits
work_n1 <- work_n1 %>% complete(date = seq(min(date), max(date) +9, by = "1 day"))
date_vec_n1 <- work_n1$date
work_n2 <- work_n2 %>% complete(date = seq(min(date), max(date) +9, by = "1 day"))
date_vec_n2 <- work_n2$date

#create a new smooth dataframe to layer
smooth_frame_n1 <- data.frame(date_vec_n1, n1_trend)
smooth_frame_n2 <- data.frame(date_vec_n2, n2_trend)

#plot smooth frames
p99 <- plotly::plot_ly() %>%
  plotly::add_lines(x = ~date_vec_n1, y = ~n1_trend,
                    data = smooth_frame_n1,
                    hoverinfo = "text",
                    text = ~paste('</br> Date: ', date_vec_n1,
                                  '</br> Copies/L: ', round(n1_trend, digits = 2)),
                    line = list(color = '#1B9E77', size = 8, opacity = 0.65),
                    showlegend = FALSE) %>%
plotly::add_lines(x = ~date_vec_n2, y = ~n2_trend,
                  data = smooth_frame_n2,
                    hoverinfo = "text",
                    text = ~paste('</br> Date: ', date_vec_n2,
                                  '</br> Copies/L: ', round(n2_trend, digits = 2)),
                    line = list(color = '#D95F02', size = 8, opacity = 0.65),
                    showlegend = FALSE) %>%
                layout(yaxis = list(title = "Log SARS CoV-2 Copies/L", 
                                 showline = TRUE,
                                 automargin = TRUE)) %>%
                layout(xaxis = list(title = "Date"))

p99
```

```{r}
smooth_extract <-
    plotly::subplot(p99,p1, # plots to combine, top to bottom
      nrows = 2,
      heights = c(.6,.4),  # relative heights of the two plots
      shareX = TRUE,  # plots will share an X axis
      titleY = TRUE
    ) %>%
    # create a vertical "spike line" to compare data across 2 plots
    plotly::layout(
      xaxis = list(
        spikethickness = 1,
        spikedash = "dot",
        spikecolor = "black",
        spikemode = "across+marker",
        spikesnap = "cursor"
      ),
      yaxis = list(spikethickness = 0)
    )

smooth_extract


```

```{r}
save(smooth_extract, file = "./smooth_extract.rda")
```

## Static options
```{r}
mindate <- min(raw_data$date)
maxdate <- max(raw_data$date)
#static trend plot using loess span 0.8
trend_plot <- ggplot(smooth_n1, aes(x = date, y = log_sum_copies_L)) + 
  geom_smooth(color = '#1B9E77', span = 0.8) +
  geom_point(color = '#1B9E77') +
  geom_smooth(data = smooth_n2, color = '#D95F02', span = 0.8) +
  geom_point(data = smooth_n2, color = '#D95F02', span = 0.8)

trend_plot <- trend_plot + theme_classic() + xlab("Date") + ylab("Log Copies/L") + 
  scale_x_date(limits = c(mindate, maxdate))

trend_plot 
```


```{r}
#static epi curve for facet wrapping
epi_curve <- ggplot(only_background, aes(x = date, y = new_cases_clarke)) + 
  geom_bar(stat = "identity", fill = "#7570B3", alpha = 0.5) +
  geom_line(aes(x = date, y = X10_day_ave_clarke), color = "#E6AB02") +
  xlab("Date") + ylab("Athens Daily Cases") +
  theme_classic()

epi_curve

smooth_stack <- gridExtra::grid.arrange(trend_plot, epi_curve, nrow =2)

smooth_stack
```

```{r}
ggsave(smooth_stack, file = "./smooth_stack.png")
```


```{r}
combogg <- ggplot(both_clean, aes(date, log_sum_copies_L)) + 
         geom_smooth(method = "loess", span = 0.8, color = '#1B9E77', alpha = 0.5, size = 1) +
         geom_point(size=1) +
  scale_x_date(limits = c(mindate, maxdate))

combo_gg_plotly <- ggplotly(combogg)
combo_gg_plotly

epi_gg_plotly <- ggplotly(epi_curve)

combo_combo <-
    plotly::subplot(combo_gg_plotly,epi_gg_plotly, # plots to combine, top to bottom
      nrows = 2,
      heights = c(.6,.4),  # relative heights of the two plots
      shareX = TRUE,  # plots will share an X axis
      titleY = TRUE
    ) %>%
    # create a vertical "spike line" to compare data across 2 plots
    plotly::layout(
      xaxis = list(
        spikethickness = 1,
        spikedash = "dot",
        spikecolor = "black",
        spikemode = "across+marker",
        spikesnap = "cursor"
      ),
      yaxis = list(spikethickness = 0)
    )

combo_combo
```